# config.yaml
bounds:
  width_r: [0, 1.5]
  SFp: [0, 6]
  CSp: [0, 200]
  width_l: [0, 1.5]       # fixed parameter in our model
  crf_exp: [0, 5]
  amplitude: [0, 10]
  baseline: [-2, 2]

n_vx: 10

hrf_model:
  tr: 1.5

simulation:
  noise: 0.1

grid_fit:
  grid_points:
    width_r: 5
    SFp: 5
    CSp: 10
    width_l: 5
    crf_exp: 5
  fixed:
    amplitude: 1.0
    baseline: 0
  use_correlation_cost: true

mcmc:
  num_steps: 500
  unrolled_leapfrog_steps: 1
  step_size: 1
  max_tree_depth: 10
  target_accept_prob: 0.85
  sampler_fn: NUTS

initial_parameters:
  width_r: 1
  SFp: 2
  CSp: 100
  width_l: 0.68
  crf_exp: 1
  amplitude: 1
  baseline: 0
