# config.yaml
bounds:
  x : [-1,1]
  y : [-0.56, 0.56]
  sd : [0.01, 2]
  amplitude: [0, 10]
  baseline: [-2, 2]

n_vx: 10

hrf_model:
  tr: 1.5

simulation:
  noise: 0.5

grid_fit:
  grid_points:
    x: 5
    y: 5
    sd: 10
  fixed:
    amplitude: 1.0
    baseline: 0
  use_correlation_cost: true

mcmc:
  num_steps: 5
  unrolled_leapfrog_steps: 1
  step_size: 1
  max_tree_depth: 10
  target_accept_prob: 0.85
  sampler_fn: NUTS

initial_parameters:
  width_r: 1
  SFp: 2
  CSp: 100
  width_l: 0.68
  crf_exp: 1
  amplitude: 1
  baseline: 0
